# Generated by Django 4.2.11 on 2024-03-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255, null=True)),
                ("genre", models.CharField(max_length=255, null=True)),
                ("publisher", models.CharField(max_length=255, null=True)),
                ("summary", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("phone_number", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.IntegerField(primary_key=True, serialize=False)),
                ("loan_date", models.DateField()),
                ("due_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.member"
                    ),
                ),
            ],
        ),
    ]
