version: '3.12'

services:

  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "admin_user"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "books"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d books || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 3


volumes:
  postgres_data:
