# Generated by Django 4.2.11 on 2024-04-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("credits", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("faculty_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=124)),
                ("last_name", models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=40)),
                ("speciality", models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "registration_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("registration_data", models.DateTimeField(auto_now_add=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                ("schedule_id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.faculty",
                    ),
                ),
                ("student_id", models.ManyToManyField(to="university.student")),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("grade_id", models.IntegerField(primary_key=True, serialize=False)),
                ("marks", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="university.faculty"
            ),
        ),
    ]
