# Generated by Django 4.2.11 on 2024-04-21 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assigning_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
