# Generated by Django 4.2.11 on 2024-05-10 15:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationkey",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
