name: Check code quality

on:
  - pull_request

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip install pipenv && pipenv install
      - name: Run formatters
        run: pipenv run black --check . && pipenv run isort --check .
      - name: Run linter
        run: pipenv run ruff .
      - name: Run static type checker
        run: pipenv run mypy .
