name: Check code quality

on:
  - pull_request

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pipenv
        run: pip install pipenv && pipenv install -d
      - name: Run formatters
        run: pipenv run black --check . && pipenv run isort --check . --profile black
